pipeline
{
    agent any
    stages
    {
        stage ("Desde GIT")
        {
            steps 
            {
                echo "Primer JOB desde GIT"
            }
        }
        stage ("Prueba Unitario")
        {
            steps
            {
                powershell ""echo "Fernando"""
            }
        }
    }
    post
    {
        always
        {
            echo "Siempre se Ejecuta independiente del resultado"
        }
        success
        {
            echo "Se ejecuta si la tarea fue satifatoria"
        }
        failure
        {
            echo "Se ejecuta si hay error"
        }
    }
}